---
deployment:
  tasks:
    - export DEPLOYPATH=/home/drbrione/public_html/appsvc.drbriones.com/
    - /bin/cp -R . $DEPLOYPATH
    - find $DEPLOYPATH -name "*.git" -type d -exec rm -rf {} + 2>/dev/null; true
